theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Instructions.md

title: Wrangling and Versioning with OpenRefine and GitHub
