theme: jekyll-theme-slate
title: CDCF Workshop: Wrangling and Versioning with OpenRefine and GitHub
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Instructions.md
